name: Ubuntu

on:
  push:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: LuisEnMarroquin/setup-ssh-action@v1.9.0
      with:
        SSHKEY: ${{ secrets.SSH_GITHUB }}
    - run: ssh -T git@github.com || true
    - uses: LuisEnMarroquin/setup-ssh-action@v1.9.0
      with:
        ORIGIN: ${{ secrets.HOST }}
        SSHKEY: ${{ secrets.SSH_SERVER }}
        NAME: production
        PORT: ${{ secrets.PORT }}
        USER: ${{ secrets.USER }}
    - run: ssh production ls --help
